/**
 * @module @aethel/vault-sdk — Aethel-Vault TypeScript Client SDK Stub
 *
 * @description
 * Vault-specific TypeScript SDK stub for Aethel-Vault integration.
 *
 * ## HelixDB TypeScript SDK Note
 *
 * The canonical HelixDB TypeScript SDK — `AethelClientSDK` with methods
 * `mapCoeffsToVector256()`, `createIngestionPayload()`, and
 * `verifySaapProof()` — is the **shared SDK** that lives in:
 *
 * ```
 * aethel-id/src/sdk/client.ts
 * ```
 *
 * This SDK serves both `aethel-id` and `aethel-vault` because:
 * - HelixDB is a shared storage layer used by both subsystems
 * - `mapCoeffsToVector256` and `createIngestionPayload` operate on M-LWE
 *   polynomial coefficients generated by the Aethel-ID PLP engine
 * - `verifySaapProof` verifies SAAP proofs, which are an Aethel-ID primitive
 *
 * This file provides **vault-specific utilities** that extend the shared SDK:
 * - `serializeContractPayload()` — bincode-compatible payload serialization
 * - `generateEphemeralVaultId()` — anonymous vault ID generation
 * - `VaultSdkClient` — thin wrapper combining WASM client + HelixDB SDK
 *
 * @example
 * ```typescript
 * import { VaultSdkClient } from '@aethel/vault-sdk';
 * import init, { AethelVaultClient } from '../pkg/aethel_vault.js';
 *
 * await init();
 * const wasmClient = new AethelVaultClient();
 * const sdk = new VaultSdkClient(wasmClient, {
 *   nodeEndpoint: 'https://helix.aethel.network'
 * });
 *
 * // Encrypt and register a vault balance
 * const contextTag = await sdk.generateContextTag(BigInt(1000));
 * const vaultId = await sdk.generateEphemeralVaultId(contextTag);
 * const encryptedBalance = sdk.encryptBalance(BigInt(10000));
 * await sdk.registerVault(vaultId, encryptedBalance);
 * ```
 *
 * @see {@link ../../aethel-id/src/sdk/client.ts} — Canonical HelixDB SDK
 * @see {@link ../client.rs} — Rust TFHE client SDK (wasm-bindgen)
 * @see {@link ../storage/helixdb.rs} — HelixDB gRPC adapter
 *
 * @dependencies
 * - `@noble/hashes ^1.4.0` — SHA3-256 for context tag and vault ID generation
 * - `typescript ^5.4.0` — TypeScript 5.x type system
 *
 * @version 0.1.0-draft
 * @author K. Harper et al. — Aytch4K Labs
 * @license Apache-2.0
 */

import { sha3_256 } from '@noble/hashes/sha3';

// ── Constants ─────────────────────────────────────────────────────────────────

/** Domain separator for vault context tag derivation. */
const VAULT_CONTEXT_DOMAIN = 'AETHEL_VAULT_CONTEXT_V1';

/** Domain separator for ephemeral vault ID derivation. */
const VAULT_ID_DOMAIN = 'AETHEL_VAULT_ID_V1';

/** Expected context tag length in bytes. */
const CONTEXT_TAG_LENGTH = 32;

// ── Type Definitions ──────────────────────────────────────────────────────────

/**
 * Configuration for the Aethel-Vault SDK client.
 */
export interface VaultSdkConfig {
  /** HelixDB gRPC/HTTP endpoint URL. */
  nodeEndpoint: string;
  /** Optional request timeout in milliseconds (default: 5000). */
  timeoutMs?: number;
  /** Optional API key for authenticated endpoints. */
  apiKey?: string;
}

/**
 * Serialized ContractPayload for submission to the vault WASM contract.
 *
 * Corresponds to the Rust `ContractPayload` struct:
 * ```rust
 * pub struct ContractPayload {
 *     pub context_tag: [u8; 32],
 *     pub encrypted_amount: Vec<u8>,
 *     pub encrypted_target: Vec<u8>,
 * }
 * ```
 */
export interface ContractPayload {
  /** 32-byte context tag τ (Uint8Array). */
  contextTag: Uint8Array;
  /** Serialized FheUint64 ciphertext for the transfer amount. */
  encryptedAmount: Uint8Array;
  /** Serialized FheUint64 ciphertext for the target account identifier. */
  encryptedTarget: Uint8Array;
}

/**
 * Parameters for vault registration.
 */
export interface RegisterVaultParams {
  /** Anonymous ephemeral vault ID (32-byte Uint8Array). */
  vaultId: Uint8Array;
  /** Serialized FheUint64 initial balance ciphertext. */
  encryptedBalance: Uint8Array;
}

/**
 * Parameters for a homomorphic transfer.
 */
export interface TransferParams {
  /** Sender vault ID (Uint8Array). */
  senderVaultId: Uint8Array;
  /** Receiver vault ID (Uint8Array). */
  receiverVaultId: Uint8Array;
  /** Serialized FheUint64 transfer amount ciphertext. */
  encryptedAmount: Uint8Array;
}

// ── Payload Serialization ─────────────────────────────────────────────────────

/**
 * Serialize a `ContractPayload` into a bincode-compatible binary format
 * for submission to the vault WASM contract.
 *
 * Binary layout (little-endian):
 * ```
 * [context_tag: 32 bytes]
 * [amount_len: 8 bytes u64 LE]
 * [encrypted_amount: amount_len bytes]
 * [target_len: 8 bytes u64 LE]
 * [encrypted_target: target_len bytes]
 * ```
 *
 * @param payload - The ContractPayload to serialize
 * @returns Serialized binary payload as Uint8Array
 * @throws {Error} If context_tag is not exactly 32 bytes
 */
export function serializeContractPayload(payload: ContractPayload): Uint8Array {
  if (payload.contextTag.length !== CONTEXT_TAG_LENGTH) {
    throw new Error(
      `Context tag must be exactly ${CONTEXT_TAG_LENGTH} bytes, got ${payload.contextTag.length}`
    );
  }

  const amountLen = payload.encryptedAmount.length;
  const targetLen = payload.encryptedTarget.length;
  const totalLen = CONTEXT_TAG_LENGTH + 8 + amountLen + 8 + targetLen;

  const result = new Uint8Array(totalLen);
  const view = new DataView(result.buffer);
  let offset = 0;

  // context_tag: 32 bytes
  result.set(payload.contextTag, offset);
  offset += CONTEXT_TAG_LENGTH;

  // amount_len: 8 bytes u64 LE
  view.setBigUint64(offset, BigInt(amountLen), true);
  offset += 8;

  // encrypted_amount: amountLen bytes
  result.set(payload.encryptedAmount, offset);
  offset += amountLen;

  // target_len: 8 bytes u64 LE
  view.setBigUint64(offset, BigInt(targetLen), true);
  offset += 8;

  // encrypted_target: targetLen bytes
  result.set(payload.encryptedTarget, offset);

  return result;
}

// ── Vault ID Generation ───────────────────────────────────────────────────────

/**
 * Generate an anonymous ephemeral vault ID from a context tag and nonce.
 *
 * The vault ID is a 32-byte SHA3-256 hash of the domain separator,
 * context tag, and nonce. It is an ephemeral identifier with no relation
 * to any public key or persistent identity.
 *
 * ```
 * vault_id = SHA3-256("AETHEL_VAULT_ID_V1" || context_tag || nonce)
 * ```
 *
 * @param contextTag - 32-byte context tag τ
 * @param nonce - Random nonce bytes (minimum 16 bytes recommended)
 * @returns 32-byte ephemeral vault ID as Uint8Array
 */
export function generateEphemeralVaultId(
  contextTag: Uint8Array,
  nonce: Uint8Array,
): Uint8Array {
  const domainBytes = new TextEncoder().encode(VAULT_ID_DOMAIN);
  const input = new Uint8Array(
    domainBytes.length + contextTag.length + nonce.length
  );
  let offset = 0;
  input.set(domainBytes, offset); offset += domainBytes.length;
  input.set(contextTag, offset); offset += contextTag.length;
  input.set(nonce, offset);
  return sha3_256(input);
}

/**
 * Generate a context tag τ from a block height and optional domain separator.
 *
 * ```
 * τ = SHA3-256("AETHEL_VAULT_CONTEXT_V1" || block_height_le64 || domain)
 * ```
 *
 * @param blockHeight - Current block height as BigInt
 * @param domain - Optional additional domain separator bytes
 * @returns 32-byte context tag as Uint8Array
 */
export function generateContextTag(
  blockHeight: bigint,
  domain?: Uint8Array,
): Uint8Array {
  const domainBytes = new TextEncoder().encode(VAULT_CONTEXT_DOMAIN);
  const blockBytes = new Uint8Array(8);
  new DataView(blockBytes.buffer).setBigUint64(0, blockHeight, true);
  const extraDomain = domain ?? new Uint8Array(0);

  const input = new Uint8Array(
    domainBytes.length + 8 + extraDomain.length
  );
  let offset = 0;
  input.set(domainBytes, offset); offset += domainBytes.length;
  input.set(blockBytes, offset); offset += 8;
  input.set(extraDomain, offset);
  return sha3_256(input);
}

// ── VaultSdkClient ────────────────────────────────────────────────────────────

/**
 * Vault SDK client — thin wrapper combining the WASM `AethelVaultClient`
 * with vault-specific payload utilities.
 *
 * For HelixDB storage operations (state node ingestion, vector proximity
 * search, SAAP proof verification), use the shared `AethelClientSDK` from
 * `aethel-id/src/sdk/client.ts`.
 *
 * @example
 * ```typescript
 * import init, { AethelVaultClient } from '../pkg/aethel_vault.js';
 * import { VaultSdkClient } from './client.js';
 *
 * await init();
 * const wasmClient = new AethelVaultClient();
 * const sdk = new VaultSdkClient(wasmClient);
 *
 * const contextTag = generateContextTag(BigInt(1000));
 * const vaultId = generateEphemeralVaultId(contextTag, crypto.getRandomValues(new Uint8Array(32)));
 * const encryptedBalance = sdk.encryptBalance(BigInt(10000));
 * ```
 */
export class VaultSdkClient {
  // NOTE: wasmClient type is `any` here because the wasm-bindgen generated
  // AethelVaultClient type is only available after `await init()` in the
  // consuming application. Import and type it from the generated pkg/ directory.
  private readonly wasmClient: any;
  private readonly config: VaultSdkConfig;

  /**
   * Create a new VaultSdkClient.
   *
   * @param wasmClient - Initialized `AethelVaultClient` instance from WASM pkg
   * @param config - Optional SDK configuration
   */
  constructor(wasmClient: any, config: VaultSdkConfig = { nodeEndpoint: '' }) {
    this.wasmClient = wasmClient;
    this.config = config;
  }

  /**
   * Encrypt a u64 balance using the WASM client's CompactPublicKey.
   *
   * @param amount - Plaintext balance as BigInt (u64 range: 0 to 2^64-1)
   * @returns Serialized FheUint64 ciphertext as Uint8Array
   */
  encryptBalance(amount: bigint): Uint8Array {
    return this.wasmClient.encrypt_u64_balance(amount);
  }

  /**
   * Decrypt a FheUint64 ciphertext using the WASM client's ClientKey.
   *
   * @param encryptedBytes - Serialized FheUint64 ciphertext
   * @returns Plaintext balance as BigInt
   */
  decryptBalance(encryptedBytes: Uint8Array): bigint {
    return this.wasmClient.decrypt_u64_balance(encryptedBytes);
  }

  /**
   * Build a serialized ContractPayload for vault contract submission.
   *
   * @param contextTag - 32-byte context tag τ
   * @param amount - Transfer amount as BigInt
   * @param targetAccount - Target account identifier as BigInt
   * @returns Serialized ContractPayload as Uint8Array
   */
  buildPayload(
    contextTag: Uint8Array,
    amount: bigint,
    targetAccount: bigint,
  ): Uint8Array {
    return this.wasmClient.build_wasm_payload(contextTag, amount, targetAccount);
  }

  /**
   * Generate a context tag for the given block height.
   *
   * @param blockHeight - Current block height
   * @param domain - Optional additional domain separator
   * @returns 32-byte context tag
   */
  generateContextTag(blockHeight: bigint, domain?: Uint8Array): Uint8Array {
    return generateContextTag(blockHeight, domain);
  }

  /**
   * Generate an anonymous ephemeral vault ID.
   *
   * @param contextTag - 32-byte context tag
   * @param nonce - Random nonce (minimum 16 bytes)
   * @returns 32-byte ephemeral vault ID
   */
  generateVaultId(contextTag: Uint8Array, nonce: Uint8Array): Uint8Array {
    return generateEphemeralVaultId(contextTag, nonce);
  }
}

// ── Re-exports ────────────────────────────────────────────────────────────────

export {
  serializeContractPayload as serialize,
  generateEphemeralVaultId as vaultId,
  generateContextTag as contextTag,
};
